In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
gdelt_df = pd.read_csv('/Users/boazmuller/thesis/data/raw/gdelt/gdelt_ai_headlines_100_per_day_2024_04_01_to_2026_04_01.csv')
gdelt_df.head()

,gdelt_date,SourceCommonName,headline,url,GKGRECORDID,V2Themes,V2Persons,V2Organizations,V2Locations,AllNames,V2Tone
0,2024-04-01,africa.com,Artificial intelligence,https://www.africa.com/how-smes-can-transform-...,20240401191500-1788,"TAX_FNCACT_DIRECTOR,37;WB_1921_PRIVATE_SECTOR_...","Dumisani Moyo,16",NaN,NaN,"Dumisani Moyo,17;Marketing Director,41;Capital...","5.3835800807537,7.40242261103634,2.01884253028..."
1,2024-04-01,allafrica.com,Rwanda: Can Artificial Intelligence Play a Rol...,https://allafrica.com/stories/202404010032.html,20240401084500-651,"UNGP_FORESTS_RIVERS_OCEANS,1672;UNGP_FORESTS_R...","Theoneste Maniragaba,4253;Johns Hopkins,575;Ja...","International Cancer Conference,244;Rwanda Bio...",1#French#FR#FR##46#2#FR#1843;1#China#CH#CH##35...,"Artificial Intelligence,57;Cancer Conference,2...","-2.02991452991453,2.77777777777778,4.807692307..."
2,2024-04-01,androidheadlines.com,US Congress may ban Microsoft Copilot citing s...,https://www.androidheadlines.com/2024/04/us-co...,20240401220000-1814,"UNGP_FORESTS_RIVERS_OCEANS,1140;TAX_FNCACT_CHI...","Catherine Szpindor,389","Us Congress,54;Us Congress,176;Us Congress,288...",NaN,"Microsoft Copilot,220;Congres Chief Administra...","-2.34604105571848,2.34604105571848,4.692082111..."
3,2024-04-01,aninews.in,Incture won Top 3 at SAP Generative AI Hack2Bu...,https://www.aninews.in/news/business/incture-w...,20240401120000-341,"TECH_AUTOMATION,711;SOC_INNOVATION,524;SOC_INN...","Konappana Agrahara,2673","Life Sciences,1823;Incture Technologies Privat...",1#Germany#GM#GM##51.5#10.5#GM#2398;4#Bangalore...,"Intelligent Onboarding Assistant,1261;Life Sci...","4.38799076212471,4.6189376443418,0.23094688221..."
4,2024-04-01,bgr.com,Apple says its new AI model ReALM is better th...,https://bgr.com/tech/apple-says-its-latest-ai-...,20240401180000-975,"SCIENCE,17;SCIENCE,576;SCIENCE,1466;TAX_FNCACT...",NaN,NaN,NaN,NaN,"1.16731517509728,2.14007782101167,0.9727626459..."

In [3]:
print(gdelt_df.shape)
gdelt_corrected = gdelt_df[['gdelt_date', 'headline']].drop_duplicates()
print(gdelt_corrected.shape)

removed = len(gdelt_df) - len(gdelt_corrected)
print(removed)

dupes = gdelt_df[
    gdelt_df.duplicated(subset=['gdelt_date', 'headline'], keep=False)
].sort_values(['gdelt_date', 'headline'])

print(dupes.shape)
dupes.head(20)

(70987, 11)
(58100, 2)
12887
(17350, 11)

,gdelt_date,SourceCommonName,headline,url,GKGRECORDID,V2Themes,V2Persons,V2Organizations,V2Locations,AllNames,V2Tone
6,2024-04-01,biztoc.com,A Once-in-a-Generation Investment Opportunity:...,https://biztoc.com/x/a471dfaa02fe8c1a,20240401013000-105,"TECH_AUTOMATION,306;",NaN,NaN,NaN,NaN,"1.5625,7.8125,6.25,14.0625,10.9375,1.5625,54"
7,2024-04-01,biztoc.com,A Once-in-a-Generation Investment Opportunity:...,https://biztoc.com/x/7ff547ea022bab07,20240401194500-677,"TECH_AUTOMATION,306;",NaN,NaN,NaN,NaN,"1.5625,7.8125,6.25,14.0625,10.9375,1.5625,54"
11,2024-04-01,biztoc.com,Forget Nvidia: Billionaires Are Selling It and...,https://biztoc.com/x/2c3f783a924efdbb,20240401101500-690,"WB_2433_CONFLICT_AND_VIOLENCE,350;WB_2465_REVO...",NaN,NaN,NaN,"Wall Street,329","3.07692307692308,6.15384615384615,3.0769230769..."
12,2024-04-01,biztoc.com,Forget Nvidia: Billionaires Are Selling It and...,https://biztoc.com/x/0e1bfc7940bda32a,20240401110000-465,"EPU_ECONOMY_HISTORIC,230;WB_2433_CONFLICT_AND_...",NaN,NaN,NaN,"Wall Street,329","3.07692307692308,6.15384615384615,3.0769230769..."
38,2024-04-01,fool.com,Forget Nvidia: Billionaires Are Selling It and...,https://www.fool.com/investing/2024/04/01/forg...,20240401173000-464,"EPU_POLICY_SPENDING,5411;EPU_POLICY_SPENDING,6...","Chase Coleman,2305;Ken Griffin,6197;David Tepp...","Intel,2662;Susquehanna International,2091;Susq...",NaN,"Wall Street,328;Millennium Management,2152;Sus...","0.76219512195122,2.89634146341463,2.1341463414..."
29,2024-04-01,dailypolitical.com,"Mcrae Capital Management Inc. Invests $174,000...",https://www.dailypolitical.com/2024/04/01/mcra...,20240401211500-505,"TAX_FNCACT_ANALYSTS,2650;TAX_FNCACT_ANALYSTS,3...",NaN,"Mcrae Capital Management Inc,28;Alamos Gold In...","4#Mulatos, Sonora, Mexico#MX#MX26#20970#28.65#...","Mcrae Capital Management,25;Alamos Gold,80;Fre...","4.31738623103851,4.55075845974329,0.2333722287..."
86,2024-04-01,themarketsdaily.com,"Mcrae Capital Management Inc. Invests $174,000...",https://www.themarketsdaily.com/2024/04/01/mcr...,20240401211500-839,"TAX_ECON_PRICE,1821;TAX_ECON_PRICE,1859;TAX_EC...",NaN,"Royal Bank,3439;Exchange Commission,230;Third ...",1#Mexico#MX#MX##23#-102#MX#4184;1#Mexico#MX#MX...,"Mcrae Capital Management,25;Alamos Gold,80;Fre...","4.31738623103851,4.55075845974329,0.2333722287..."
35,2024-04-01,finanznachrichten.de,OpenAI Prolongs The Release Of Voice Cloning Tool,https://www.finanznachrichten.de/nachrichten-2...,20240401200000-1694,"WB_678_DIGITAL_GOVERNMENT,1116;WB_670_ICT_SECU...","Dennis Riedl,2267;Dennis Riedl,2430",NaN,"3#Washington, Washington, United States#US#USD...","Voice Engine,250","0,1.93704600484262,1.93704600484262,3.87409200..."
68,2024-04-01,rttnews.com,OpenAI Prolongs The Release Of Voice Cloning Tool,https://www.rttnews.com/3436058/openai-prolong...,20240401221500-945,"TAX_FNCACT_SPEAKER,1113;TAX_FNCACT_SPEAKER,154...",NaN,NaN,1#German#GM#GM##51.5#10.5#GM#1477;1#Japanese#J...,"Voice Engine,234","0,1.92837465564738,1.92837465564738,3.85674931..."
59,2024-04-01,news18.com,OpenAI Removes Sam Altman's Ownership of Its S...,https://www.news18.com/tech/openai-removes-sam...,20240401174500-2140,"WB_696_PUBLIC_SECTOR_MANAGEMENT,33;WB_831_GOVE...","Sam Altman,143;Ian Hathaway,1058","Openai Startup Fund,351;Openai Startup Fund,88...",NaN,"Sam Altman,145;Exchange Commission,254;Ian Hat...","2.10526315789474,3.15789473684211,1.0526315789..."
91,2024-04-01,usnews.com,OpenAI Removes Sam Altman's Ownership of Its S...,https://money.usnews.com/investing/news/articl...,20240401181500-993,"TAX_FNCACT_EXECUTIVE,346;TAX_FNCACT_CHIEF_EXEC...","Sam Altman,31;Sam Altman,357;Josie Kao,2036;Ia...","Exchange Commission,461;World Economic Forum,1...","2#New York, United States#US#USNY##42.1497#-74...","Sam Altman,28;World Economic Forum,110;Sam Alt...","1.82926829268293,2.74390243902439,0.9146341463..."
55,2024-04-01,marketscreener.com,OpenAI removes Sam Altman's ownership of its S...,https://www.marketscreener.com/quote/stock/MIC...,20240401190000-1714,"TAX_FNCACT_INVESTOR,739;LEADER,1083;TAX_FNCACT...","Josie Kao,1566;Ian Hathaway,795","Helion Energy,1267;Microsoft,695;Openai Startu...","2#New York, United States#US#USNY##42.1497#-74...","Ian Hathaway,824;Helion Energy,1316;New York,1...","1.953125,3.125,1.171875,4.296875,24.609375,0,238"
77,2024-04-01,streetinsider.com,OpenAI removes Sam Altman's ownership of its S...,https://www.streetinsider.com/Reuters/OpenAI+r...,20240401163000-661,"EPU_CATS_REGULATION,277;EPU_CATS_FINANCIAL_REG...","Ian Hathaway,1077;Josie Kao,1848;Sam Altman,169","Openai Startup Fund,377;Openai Startup Fund,90...","2#New York, United States#US#USNY##42.1497#-74...","Sam Altman,177;Exchange Commission,286;Ian Hat...","2.0066889632107,3.01003344481605,1.00334448160..."
27,2024-04-01,cnn.com,OpenAI says it's working on AI that mimics hum...,https://www.cnn.com/2024/04/01/tech/openai-ai-...,20240401160000-367,"TAX_WORLDBIRDS_SORA,2777;TAX_WORLDBIRDS_SORA,2...",NaN,NaN,1#French#FR#FR##46#2#FR#2592;1#German#GM#GM##5...,"Voice Engine,381;Voice Engine,1118;Voice Engin...","0.196463654223968,2.55402750491159,2.357563850..."
53,2024-04-01,ktvz.com,OpenAI says it's working on AI that mimics hum...,https://ktvz.com/money/cnn-business-consumer/2...,20240401233000-828,"ELECTION,1656;EPU_CATS_MIGRATION_FEAR_FEAR,100...","Clare Duffy,14","Cnn,20;Cnn,35",1#French#FR#FR##46#2#FR#2635;1#Japanese#JA#JA#...,"Clare Duffy,15;Voice Engine,424;Voice Engine,1...","0.457317073170732,2.28658536585366,1.829268292..."
94,2024-04-01,wral.com,OpenAI says it's working on AI that mimics hum...,https://www.wral.com/story/openai-says-its-wor...,20240401194500-1903,"WB_1331_HEALTH_TECHNOLOGIES,1054;WB_621_HEALTH...",NaN,"Discovery Company,3045;Warner Bros,3026",1#Spanish#SP#SP##40#-4#SP#2431;1#French#FR#FR#...,"New York,9;Voice Engine,245;Voice Engine,967;V...","0.78740157480315,2.36220472440945,1.5748031496..."
191,2024-04-02,webindia123.com,"""GISEC 2024"" examines growing impact of artifi...",https://news.webindia123.com/news/Articles/Wor...,20240402181500-971,"LEADER,1110;TAX_FNCACT_PRESIDENT,1110;USPEC_PO...","Christian Borst,2362;Charles Brooks,1098","Brooks Consulting International,1145;Georgetow...","3#Washington, Washington, United States#US#USD...","Dubai World Trade Center,110;Resilience Based,...","-2.90556900726392,4.60048426150121,7.506053268..."
194,2024-04-02,wn.com,"""GISEC 2024"" examines growing impact of artifi...",https://article.wn.com/view/2024/04/02/GISEC_2...,20240402194500-1648,"WB_698_TRADE,116;TAX_ETHNICITY_ARAB,18;TAX_ETH...",NaN,NaN,"4#Dubai, Dubayy, United Arab Emirates#AE#AE03#...","Dubai World Trade Center,109","-2.85714285714286,0,2.85714285714286,2.8571428..."
196,2024-04-02,yourstory.com,"Embracing GenAI to transform work, workers, an...",https://social.yourstory.com:443/2024/04/embra...,20240402190000-2038,"CRISISLEX_C07_SAFETY,3261;TAX_FNCACT_WORKERS,1...","Lakshmi Chandrasekharan,204","Accenture,269;Accenture,1109;Accenture,2231",1#India#IN#IN##20#77#IN#278,"Lakshmi Chandrasekharan,220;Managing Director,...","3.96196513470682,6.81458003169572,2.8526148969..."
197,2024-04-02,yourstory.com,"Embracing GenAI to transform work, workers, an...",https://yourstory.com:443/2024/04/embracing-ge...,20240402211500-958,"SOC_EMERGINGTECH,1402;UNGP_FORESTS_RIVERS_OCEA...","Lakshmi Chandrasekharan,204","Accenture,269;Accenture,1109;Accenture,2231",1#India#IN#IN##20#77#IN#278,"Lakshmi Chandrasekharan,220;Managing Director,...","3.96196513470682,6.81458003169572,2.8526148969..."

In [4]:
headline_count_by_day = gdelt_corrected['gdelt_date'].value_counts(sort = True, ascending = True)
print(headline_count_by_day.describe())

count    714.000000
mean      81.372549
std       11.869965
min       26.000000
25%       75.250000
50%       84.000000
75%       91.000000
max      100.000000
Name: count, dtype: float64

In [32]:
gdelt_df.isna().any()

gdelt_date          False
SourceCommonName    False
headline            False
url                 False
GKGRECORDID         False
V2Themes             True
V2Persons            True
V2Organizations      True
V2Locations          True
AllNames             True
V2Tone              False
dtype: bool